language: php

php:
    - 7.0
    - 7.1
    - 7.2

install:
    - composer install

script:
    - for file in $(find Sniffs/ -name \*.php); do php -l $file > /dev/null; done;
    - ./vendor/bin/phpcs
